accounts:
  tokenKey: 'dev_auth_token'
  passwordResetEmailEnabled: false

sms:
  enabled: false

mongoDb:
  uri: 'mongodb://localhost:27017/workout-planner-dev'


webAppHost: 'http://localhost:3000'
